/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.vendas.view;

import br.com.vendas.dao.ClientesDAO;
import br.com.vendas.dao.FuncionariosDAO;

import br.com.vendas.model.Funcionarios;
import br.com.vendas.model.Utilitarios;
import java.awt.event.KeyEvent;
import javax.swing.table.DefaultTableModel;
import java.util.List;
import javax.swing.JOptionPane;
/**
 *
 * @author Giovane Oliveira
 */
public class FrmCadastroFuncionario extends javax.swing.JFrame {

    /**
     * Creates new form Frmcliente
     */
    public FrmCadastroFuncionario() {
        initComponents();       
    }
    
    
    public void limparCampos(){
    
       /*Codigotxt1.setText("");
        Nometxt1.setText("");
        Rgtxt1.setText("");
       Cpftxt1.setText("");
        Emailtxt1.setText("");
        Telefonetxt1.setText("");
        Celulartxt1.setText("");
        Ceptxt1.setText("");
        Enderecotxt1.setText("");
        Numerotxt1.setText("");
        Complementotxt1.setText("");
       Bairrotxt1.setText("");
        Cidadetxt1.setText("");*/
       
       new Utilitarios().LimpaTela(PainelCadastroFuncionarios);
       
    
    
    
    }
    
    
   public void listar(){
   
   FuncionariosDAO dao =  new FuncionariosDAO();
   List<Funcionarios> lista = dao.listarFuncionarios();
   DefaultTableModel dados = (DefaultTableModel) TabelaFuncionarios.getModel();
   dados.setNumRows(0);
   for(Funcionarios c : lista){
   
   dados.addRow(new Object[]{
   c.getId(),
   c.getNome(),
   c.getRg(),
   c.getCpf(),
   c.getEmail(),
   c.getSenha(),
   c.getCargo(),
   c.getTipoUsuario(),
   c.getTelefone(),
   c.getCelular(),
   c.getCep(),
   c.getEndereco(),
   c.getNumero(),
   c.getComplemento(),
   c.getBairro(),
   c.getCidade(),
   c.getEstado()
   
           
   
   });
   }
   
   
   }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Funcionarios = new javax.swing.JTabbedPane();
        PainelCadastroFuncionarios = new javax.swing.JPanel();
        CodigoFuncionario = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        NomeFuncionario = new javax.swing.JTextField();
        BtnFuncionario = new javax.swing.JButton();
        EmailFuncionario = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        CelularFuncionario = new javax.swing.JFormattedTextField();
        jLabel34 = new javax.swing.JLabel();
        CepFuncionario = new javax.swing.JFormattedTextField();
        jLabel35 = new javax.swing.JLabel();
        CpfFuncionario = new javax.swing.JFormattedTextField();
        jLabel36 = new javax.swing.JLabel();
        RgFuncionario = new javax.swing.JFormattedTextField();
        ComplementoFuncionario = new javax.swing.JTextField();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        BairroFuncionario = new javax.swing.JTextField();
        jLabel39 = new javax.swing.JLabel();
        EnderecoFuncionario = new javax.swing.JTextField();
        jLabel40 = new javax.swing.JLabel();
        CidadeFuncionario = new javax.swing.JTextField();
        EstadoFuncionario = new javax.swing.JComboBox<>();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        TelefoneFuncionario = new javax.swing.JFormattedTextField();
        BtnNovoFuncionario = new javax.swing.JButton();
        BtnSalvarFuncionario = new javax.swing.JButton();
        BtnEditarFuncionario = new javax.swing.JButton();
        BtnExcluirFuncionario = new javax.swing.JButton();
        NumeroFuncionario = new javax.swing.JFormattedTextField();
        jLabel44 = new javax.swing.JLabel();
        CargoFuncionario = new javax.swing.JTextField();
        jLabel45 = new javax.swing.JLabel();
        tipoUsuarioFuncionario = new javax.swing.JComboBox<>();
        jLabel46 = new javax.swing.JLabel();
        SenhaFuncionario = new javax.swing.JPasswordField();
        ConsultaFuncionario = new javax.swing.JPanel();
        PainelPesquisaClientes = new javax.swing.JLabel();
        txtpesquisar = new javax.swing.JTextField();
        btnPesquisar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TabelaFuncionarios = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Cadastro de Funcionarios");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 558, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Funcionarios.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                FuncionariosStateChanged(evt);
            }
        });

        CodigoFuncionario.setEditable(false);

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel15.setText("Código:");

        jLabel31.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel31.setText("Nome:");

        BtnFuncionario.setText("Pesquisar");
        BtnFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnFuncionarioActionPerformed(evt);
            }
        });

        jLabel32.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel32.setText("E-mail:");

        jLabel33.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel33.setText("Celular:");

        try {
            CelularFuncionario.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)#####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel34.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel34.setText("Cep:");

        try {
            CepFuncionario.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        CepFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CepFuncionarioActionPerformed(evt);
            }
        });
        CepFuncionario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                CepFuncionarioKeyPressed(evt);
            }
        });

        jLabel35.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel35.setText("CPF:");

        try {
            CpfFuncionario.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        CpfFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CpfFuncionarioActionPerformed(evt);
            }
        });

        jLabel36.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel36.setText("RG:");

        try {
            RgFuncionario.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-#")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel37.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel37.setText("Complemento:");

        jLabel38.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel38.setText("Bairro:");

        jLabel39.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel39.setText("Endereço:");

        EnderecoFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EnderecoFuncionarioActionPerformed(evt);
            }
        });

        jLabel40.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel40.setText("Cidade:");

        EstadoFuncionario.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "AC", "AL", "AP", "AM", "BA", "CE", "DF", "ES", "GO", "MA", "MT", "MS", "MG", "PA", "PB", "PR", "PE", "PI", "RJ", "RN", "RS", "RO", "RR", "SC", "SP", "SE", "TO" }));
        EstadoFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EstadoFuncionarioActionPerformed(evt);
            }
        });

        jLabel41.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel41.setText("UF:");

        jLabel42.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel42.setText("Número:");

        jLabel43.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel43.setText("Telefone fixo:");

        try {
            TelefoneFuncionario.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) ####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        BtnNovoFuncionario.setText("NOVO");
        BtnNovoFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnNovoFuncionarioActionPerformed(evt);
            }
        });

        BtnSalvarFuncionario.setText("SALVAR");
        BtnSalvarFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSalvarFuncionarioActionPerformed(evt);
            }
        });

        BtnEditarFuncionario.setText("EDITAR");
        BtnEditarFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnEditarFuncionarioActionPerformed(evt);
            }
        });

        BtnExcluirFuncionario.setText("EXCLUIR");
        BtnExcluirFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnExcluirFuncionarioActionPerformed(evt);
            }
        });

        try {
            NumeroFuncionario.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel44.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel44.setText("Cargo:");

        jLabel45.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel45.setText("Nivel de Acesso");

        tipoUsuarioFuncionario.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Usuário", "Administrador" }));

        jLabel46.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel46.setText("Senha:");

        SenhaFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SenhaFuncionarioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PainelCadastroFuncionariosLayout = new javax.swing.GroupLayout(PainelCadastroFuncionarios);
        PainelCadastroFuncionarios.setLayout(PainelCadastroFuncionariosLayout);
        PainelCadastroFuncionariosLayout.setHorizontalGroup(
            PainelCadastroFuncionariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelCadastroFuncionariosLayout.createSequentialGroup()
                .addGroup(PainelCadastroFuncionariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PainelCadastroFuncionariosLayout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addGroup(PainelCadastroFuncionariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PainelCadastroFuncionariosLayout.createSequentialGroup()
                                .addGroup(PainelCadastroFuncionariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel31)
                                    .addComponent(jLabel15))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(PainelCadastroFuncionariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(CodigoFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(PainelCadastroFuncionariosLayout.createSequentialGroup()
                                        .addComponent(NomeFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(BtnFuncionario))))
                            .addGroup(PainelCadastroFuncionariosLayout.createSequentialGroup()
                                .addComponent(jLabel32)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(EmailFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(PainelCadastroFuncionariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, PainelCadastroFuncionariosLayout.createSequentialGroup()
                                    .addGap(272, 272, 272)
                                    .addGroup(PainelCadastroFuncionariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel38)
                                        .addComponent(jLabel36)
                                        .addComponent(jLabel45))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(PainelCadastroFuncionariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(PainelCadastroFuncionariosLayout.createSequentialGroup()
                                            .addGroup(PainelCadastroFuncionariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(PainelCadastroFuncionariosLayout.createSequentialGroup()
                                                    .addComponent(BairroFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGap(18, 18, 18)
                                                    .addComponent(jLabel42)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(NumeroFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(jLabel41)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(EstadoFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGap(0, 0, Short.MAX_VALUE))
                                                .addGroup(PainelCadastroFuncionariosLayout.createSequentialGroup()
                                                    .addComponent(RgFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(jLabel37)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                    .addComponent(ComplementoFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(jLabel43)
                                            .addGap(18, 18, 18)
                                            .addComponent(TelefoneFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(PainelCadastroFuncionariosLayout.createSequentialGroup()
                                            .addComponent(tipoUsuarioFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(0, 0, Short.MAX_VALUE))))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, PainelCadastroFuncionariosLayout.createSequentialGroup()
                                    .addGroup(PainelCadastroFuncionariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(PainelCadastroFuncionariosLayout.createSequentialGroup()
                                            .addComponent(jLabel33)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(CelularFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PainelCadastroFuncionariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PainelCadastroFuncionariosLayout.createSequentialGroup()
                                                .addGap(34, 34, 34)
                                                .addGroup(PainelCadastroFuncionariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(jLabel35)
                                                    .addComponent(jLabel44)
                                                    .addComponent(jLabel46))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(PainelCadastroFuncionariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(CargoFuncionario)
                                                    .addGroup(PainelCadastroFuncionariosLayout.createSequentialGroup()
                                                        .addComponent(CpfFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGap(0, 0, Short.MAX_VALUE))
                                                    .addComponent(SenhaFuncionario)))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PainelCadastroFuncionariosLayout.createSequentialGroup()
                                                .addGap(14, 14, 14)
                                                .addComponent(jLabel34)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(CepFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGap(74, 74, 74)
                                    .addComponent(jLabel39)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(EnderecoFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jLabel40)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(CidadeFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(PainelCadastroFuncionariosLayout.createSequentialGroup()
                        .addGap(354, 354, 354)
                        .addComponent(BtnNovoFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(BtnSalvarFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(BtnEditarFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(BtnExcluirFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(57, Short.MAX_VALUE))
        );

        PainelCadastroFuncionariosLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {BtnEditarFuncionario, BtnExcluirFuncionario, BtnNovoFuncionario, BtnSalvarFuncionario});

        PainelCadastroFuncionariosLayout.setVerticalGroup(
            PainelCadastroFuncionariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelCadastroFuncionariosLayout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addGroup(PainelCadastroFuncionariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(CodigoFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PainelCadastroFuncionariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel31)
                    .addComponent(NomeFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnFuncionario))
                .addGap(13, 13, 13)
                .addGroup(PainelCadastroFuncionariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel32)
                    .addComponent(EmailFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PainelCadastroFuncionariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel33)
                    .addComponent(CelularFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel39)
                    .addComponent(EnderecoFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel40)
                    .addComponent(CidadeFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PainelCadastroFuncionariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel42, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(PainelCadastroFuncionariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel34)
                        .addComponent(CepFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel38)
                        .addComponent(BairroFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel41)
                        .addComponent(EstadoFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(NumeroFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PainelCadastroFuncionariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PainelCadastroFuncionariosLayout.createSequentialGroup()
                        .addGroup(PainelCadastroFuncionariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(CpfFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel35))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PainelCadastroFuncionariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel44)
                            .addComponent(CargoFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PainelCadastroFuncionariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel46)
                            .addComponent(SenhaFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(PainelCadastroFuncionariosLayout.createSequentialGroup()
                        .addGroup(PainelCadastroFuncionariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel43)
                            .addComponent(TelefoneFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ComplementoFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel37)
                            .addComponent(RgFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel36))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PainelCadastroFuncionariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel45)
                            .addComponent(tipoUsuarioFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 95, Short.MAX_VALUE)
                .addGroup(PainelCadastroFuncionariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnNovoFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnSalvarFuncionario)
                    .addComponent(BtnEditarFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnExcluirFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        PainelCadastroFuncionariosLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {BtnEditarFuncionario, BtnExcluirFuncionario, BtnNovoFuncionario, BtnSalvarFuncionario});

        Funcionarios.addTab("Dados Pessoais", PainelCadastroFuncionarios);

        ConsultaFuncionario.setBackground(new java.awt.Color(255, 255, 255));
        ConsultaFuncionario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ConsultaFuncionarioMouseClicked(evt);
            }
        });

        PainelPesquisaClientes.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        PainelPesquisaClientes.setText("Nome:");

        txtpesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpesquisarActionPerformed(evt);
            }
        });
        txtpesquisar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtpesquisarKeyPressed(evt);
            }
        });

        btnPesquisar.setText("Pesquisar");
        btnPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarActionPerformed(evt);
            }
        });

        TabelaFuncionarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Nome", "RG", "CPF", "E-mail", "Senha", "Cargo", "Nivel de acesso", "Telefone", "Celular", "Cep", "Endereço", "Número", "Complemento", "Bairro", "Cidade", "Estado"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TabelaFuncionarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TabelaFuncionariosMouseClicked(evt);
            }
        });
        TabelaFuncionarios.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                TabelaFuncionariosPropertyChange(evt);
            }
        });
        jScrollPane1.setViewportView(TabelaFuncionarios);

        javax.swing.GroupLayout ConsultaFuncionarioLayout = new javax.swing.GroupLayout(ConsultaFuncionario);
        ConsultaFuncionario.setLayout(ConsultaFuncionarioLayout);
        ConsultaFuncionarioLayout.setHorizontalGroup(
            ConsultaFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ConsultaFuncionarioLayout.createSequentialGroup()
                .addGroup(ConsultaFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ConsultaFuncionarioLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1227, Short.MAX_VALUE))
                    .addGroup(ConsultaFuncionarioLayout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(PainelPesquisaClientes)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtpesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnPesquisar)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        ConsultaFuncionarioLayout.setVerticalGroup(
            ConsultaFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ConsultaFuncionarioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ConsultaFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PainelPesquisaClientes)
                    .addComponent(txtpesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPesquisar))
                .addGap(49, 49, 49)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(200, Short.MAX_VALUE))
        );

        Funcionarios.addTab("Consulta Funcionario", ConsultaFuncionario);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Funcionarios, javax.swing.GroupLayout.PREFERRED_SIZE, 1252, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(Funcionarios, javax.swing.GroupLayout.PREFERRED_SIZE, 487, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void EnderecoFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EnderecoFuncionarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EnderecoFuncionarioActionPerformed

    private void CpfFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CpfFuncionarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CpfFuncionarioActionPerformed

    private void CepFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CepFuncionarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CepFuncionarioActionPerformed

    private void EstadoFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EstadoFuncionarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EstadoFuncionarioActionPerformed

    private void BtnSalvarFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSalvarFuncionarioActionPerformed
        // TODO add your handling code here:
        
        Funcionarios obj = new Funcionarios();
        obj.setNome(NomeFuncionario.getText());
        obj.setRg(RgFuncionario.getText());
        obj.setCpf(CpfFuncionario.getText());
        obj.setEmail(EmailFuncionario.getText());
        obj.setSenha(SenhaFuncionario.getText());
        obj.setCargo(CargoFuncionario.getText());
        obj.setTipoUsuario(tipoUsuarioFuncionario.getSelectedItem().toString());
        obj.setTelefone(TelefoneFuncionario.getText());
        obj.setCelular(CelularFuncionario.getText());
        obj.setCep(CepFuncionario.getText());
        obj.setEndereco(EnderecoFuncionario.getText());
        obj.setNumero(Integer.parseInt(NumeroFuncionario.getText()));
        obj.setComplemento(ComplementoFuncionario.getText());
        obj.setBairro(BairroFuncionario.getText());
        obj.setCidade(CidadeFuncionario.getText());
        obj.setEstado(EstadoFuncionario.getSelectedItem().toString());
       
        FuncionariosDAO dao = new FuncionariosDAO();
        
        dao.cadastrarFuncionario(obj);
        
        
        limparCampos();
       
      
        
        
    }//GEN-LAST:event_BtnSalvarFuncionarioActionPerformed

    private void FuncionariosStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_FuncionariosStateChanged
        // TODO add your handling code here:
        
      
        
    }//GEN-LAST:event_FuncionariosStateChanged

    private void TabelaFuncionariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TabelaFuncionariosMouseClicked
        // TODO add your handling code here:
        
       Funcionarios.setSelectedComponent(this.PainelCadastroFuncionarios);
       CodigoFuncionario.setText(TabelaFuncionarios.getValueAt(TabelaFuncionarios.getSelectedRow(),0).toString());
       NomeFuncionario.setText(TabelaFuncionarios.getValueAt(TabelaFuncionarios.getSelectedRow(),1).toString());
       RgFuncionario.setText(TabelaFuncionarios.getValueAt(TabelaFuncionarios.getSelectedRow(),2).toString());
       CpfFuncionario.setText(TabelaFuncionarios.getValueAt(TabelaFuncionarios.getSelectedRow(),3).toString());
       EmailFuncionario.setText(TabelaFuncionarios.getValueAt(TabelaFuncionarios.getSelectedRow(),4).toString());
       SenhaFuncionario.setText(TabelaFuncionarios.getValueAt(TabelaFuncionarios.getSelectedRow(),5).toString());
       CargoFuncionario.setText(TabelaFuncionarios.getValueAt(TabelaFuncionarios.getSelectedRow(),6).toString());
       tipoUsuarioFuncionario.setSelectedItem(TabelaFuncionarios.getValueAt(TabelaFuncionarios.getSelectedRow(),7).toString());
       TelefoneFuncionario.setText(TabelaFuncionarios.getValueAt(TabelaFuncionarios.getSelectedRow(),8).toString());
       CelularFuncionario.setText(TabelaFuncionarios.getValueAt(TabelaFuncionarios.getSelectedRow(),9).toString());
       CepFuncionario.setText(TabelaFuncionarios.getValueAt(TabelaFuncionarios.getSelectedRow(),10).toString());
       EnderecoFuncionario.setText(TabelaFuncionarios.getValueAt(TabelaFuncionarios.getSelectedRow(),11).toString());
       NumeroFuncionario.setText(TabelaFuncionarios.getValueAt(TabelaFuncionarios.getSelectedRow(),12).toString());
       ComplementoFuncionario.setText(TabelaFuncionarios.getValueAt(TabelaFuncionarios.getSelectedRow(),13).toString());
       BairroFuncionario.setText(TabelaFuncionarios.getValueAt(TabelaFuncionarios.getSelectedRow(),14).toString());
       CidadeFuncionario.setText(TabelaFuncionarios.getValueAt(TabelaFuncionarios.getSelectedRow(),15).toString());
       EstadoFuncionario.setSelectedItem(TabelaFuncionarios.getValueAt(TabelaFuncionarios.getSelectedRow(),16).toString());
       
    }//GEN-LAST:event_TabelaFuncionariosMouseClicked

    private void BtnEditarFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnEditarFuncionarioActionPerformed
        // TODO add your handling code here:
        Funcionarios obj = new Funcionarios();
        obj.setNome(NomeFuncionario.getText());
        obj.setRg(RgFuncionario.getText());
        obj.setCpf(CpfFuncionario.getText());
        obj.setEmail(EmailFuncionario.getText());
        obj.setSenha(SenhaFuncionario.getText());
        obj.setCargo(CargoFuncionario.getText());
        obj.setTipoUsuario(tipoUsuarioFuncionario.getSelectedItem().toString());
        obj.setTelefone(TelefoneFuncionario.getText());
        obj.setCelular(CelularFuncionario.getText());
        obj.setCep(CepFuncionario.getText());
        obj.setEndereco(EnderecoFuncionario.getText());
        obj.setNumero(Integer.parseInt(NumeroFuncionario.getText()));
        obj.setComplemento(ComplementoFuncionario.getText());
        obj.setBairro(BairroFuncionario.getText());
        obj.setCidade(CidadeFuncionario.getText());
        obj.setEstado(EstadoFuncionario.getSelectedItem().toString());
        obj.setId(Integer.parseInt(CodigoFuncionario.getText()));
       
        FuncionariosDAO dao = new FuncionariosDAO();
        
        dao.alterarFuncionario(obj);
        
        limparCampos();
        
    }//GEN-LAST:event_BtnEditarFuncionarioActionPerformed

    private void BtnExcluirFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnExcluirFuncionarioActionPerformed
        // TODO add your handling code here:
        
            Funcionarios obj = new Funcionarios();
     
        obj.setId(Integer.parseInt(CodigoFuncionario.getText()));
       
        FuncionariosDAO dao = new FuncionariosDAO();
        
        dao.excluirFuncionario(obj);
        
        
        limparCampos();
    }//GEN-LAST:event_BtnExcluirFuncionarioActionPerformed

    private void ConsultaFuncionarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ConsultaFuncionarioMouseClicked
        // TODO add your handling code here:
      
    }//GEN-LAST:event_ConsultaFuncionarioMouseClicked

    private void TabelaFuncionariosPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_TabelaFuncionariosPropertyChange
        // TODO add your handling code here:
        
       
    }//GEN-LAST:event_TabelaFuncionariosPropertyChange

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
        listar();
    }//GEN-LAST:event_formWindowActivated

    private void txtpesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpesquisarActionPerformed
        // TODO add your handling code here:

   
        
        
    }//GEN-LAST:event_txtpesquisarActionPerformed

    private void btnPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarActionPerformed
        // TODO add your handling code here:
        
   FuncionariosDAO dao =  new FuncionariosDAO();
   List<Funcionarios> lista = dao.listarFuncionariosPorNome("%" + txtpesquisar.getText() + "%");
   DefaultTableModel dados = (DefaultTableModel) TabelaFuncionarios.getModel();
   dados.setNumRows(0);
   for(Funcionarios c : lista){
   
   dados.addRow(new Object[]{
   c.getId(),
   c.getNome(),
   c.getRg(),
   c.getCpf(),
   c.getEmail(),
   c.getSenha(),
   c.getCargo(),
   c.getTipoUsuario(),
   c.getTelefone(),
   c.getCelular(),
   c.getCep(),
   c.getEndereco(),
   c.getNumero(),
   c.getComplemento(),
   c.getBairro(),
   c.getCidade(),
   c.getEstado()
   
           
   
   });
   }
        
        
    }//GEN-LAST:event_btnPesquisarActionPerformed

    private void txtpesquisarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtpesquisarKeyPressed
        // TODO add your handling code here:
        
   FuncionariosDAO dao =  new FuncionariosDAO();
   List<Funcionarios> lista = dao.listarFuncionariosPorNome("%" + txtpesquisar.getText() + "%");
   DefaultTableModel dados = (DefaultTableModel) TabelaFuncionarios.getModel();
   dados.setNumRows(0);
   for(Funcionarios c : lista){
   
   dados.addRow(new Object[]{
   c.getId(),
   c.getNome(),
   c.getRg(),
   c.getCpf(),
   c.getEmail(),
   c.getSenha(),
   c.getCargo(),
   c.getTipoUsuario(),
   c.getTelefone(),
   c.getCelular(),
   c.getCep(),
   c.getEndereco(),
   c.getNumero(),
   c.getComplemento(),
   c.getBairro(),
   c.getCidade(),
   c.getEstado()
   
           
   
   });
   }
        
        
    }//GEN-LAST:event_txtpesquisarKeyPressed

    private void BtnNovoFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnNovoFuncionarioActionPerformed
        // TODO add your handling code here:
        
        limparCampos();
    }//GEN-LAST:event_BtnNovoFuncionarioActionPerformed

    private void BtnFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnFuncionarioActionPerformed
        // TODO add your handling code here:
        FuncionariosDAO dao = new FuncionariosDAO();
        Funcionarios obj = dao.consultarFuncionariosPorNome(NomeFuncionario.getText());
        
        if(obj.getNome() != null){
        
        CodigoFuncionario.setText(String.valueOf(obj.getId()));
        NomeFuncionario.setText(obj.getNome());
        RgFuncionario.setText(obj.getRg());
       CpfFuncionario.setText(obj.getCpf());
       EmailFuncionario.setText(obj.getEmail());
       SenhaFuncionario.setText(obj.getEmail());
       CargoFuncionario.setText(obj.getEmail());
       tipoUsuarioFuncionario.setSelectedItem(obj.getEmail());
       TelefoneFuncionario.setText(obj.getTelefone());
       CelularFuncionario.setText(obj.getCelular());
       CepFuncionario.setText(obj.getCep());
       EnderecoFuncionario.setText(obj.getEndereco());
       NumeroFuncionario.setText(String.valueOf(obj.getNumero()));
       ComplementoFuncionario.setText(obj.getComplemento());
       BairroFuncionario.setText(obj.getBairro());
       CidadeFuncionario.setText(obj.getBairro());
       EstadoFuncionario.setSelectedItem(obj.getEstado());
        
        }else{
        JOptionPane.showMessageDialog(null, "Usuário não encontrado");
        
        }
        
        
    }//GEN-LAST:event_BtnFuncionarioActionPerformed

    private void CepFuncionarioKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CepFuncionarioKeyPressed
        // TODO add your handling code here:
        
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) { 
     Funcionarios obj = new FuncionariosDAO().buscaCep(CepFuncionario.getText());
      EnderecoFuncionario.setText(obj.getEndereco());
      CidadeFuncionario.setText(obj.getCidade());
      BairroFuncionario.setText(obj.getBairro());
      EstadoFuncionario.setSelectedItem(obj.getEstado()); 
     }
        
     
        
    }//GEN-LAST:event_CepFuncionarioKeyPressed

    private void SenhaFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SenhaFuncionarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SenhaFuncionarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmCadastroFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmCadastroFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmCadastroFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmCadastroFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmCadastroFuncionario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField BairroFuncionario;
    private javax.swing.JButton BtnEditarFuncionario;
    private javax.swing.JButton BtnExcluirFuncionario;
    private javax.swing.JButton BtnFuncionario;
    private javax.swing.JButton BtnNovoFuncionario;
    private javax.swing.JButton BtnSalvarFuncionario;
    private javax.swing.JTextField CargoFuncionario;
    private javax.swing.JFormattedTextField CelularFuncionario;
    private javax.swing.JFormattedTextField CepFuncionario;
    private javax.swing.JTextField CidadeFuncionario;
    private javax.swing.JTextField CodigoFuncionario;
    private javax.swing.JTextField ComplementoFuncionario;
    private javax.swing.JPanel ConsultaFuncionario;
    private javax.swing.JFormattedTextField CpfFuncionario;
    private javax.swing.JTextField EmailFuncionario;
    private javax.swing.JTextField EnderecoFuncionario;
    private javax.swing.JComboBox<String> EstadoFuncionario;
    private javax.swing.JTabbedPane Funcionarios;
    private javax.swing.JTextField NomeFuncionario;
    private javax.swing.JFormattedTextField NumeroFuncionario;
    private javax.swing.JPanel PainelCadastroFuncionarios;
    private javax.swing.JLabel PainelPesquisaClientes;
    private javax.swing.JFormattedTextField RgFuncionario;
    private javax.swing.JPasswordField SenhaFuncionario;
    private javax.swing.JTable TabelaFuncionarios;
    private javax.swing.JFormattedTextField TelefoneFuncionario;
    private javax.swing.JButton btnPesquisar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> tipoUsuarioFuncionario;
    private javax.swing.JTextField txtpesquisar;
    // End of variables declaration//GEN-END:variables
}
