/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.vendas.view;

import br.com.vendas.dao.ClientesDAO;

import br.com.vendas.model.Funcionarios;
import br.com.vendas.model.Utilitarios;
import java.awt.event.KeyEvent;
import javax.swing.table.DefaultTableModel;
import java.util.List;
import javax.swing.JOptionPane;
/**
 *
 * @author Giovane Oliveira
 */
public class Frmcliente extends javax.swing.JFrame {

    /**
     * Creates new form Frmcliente
     */
    public Frmcliente() {
        initComponents();
          
        
    }
    
    
    public void limparCampos(){
    
       /*Codigotxt1.setText("");
        Nometxt1.setText("");
        Rgtxt1.setText("");
       Cpftxt1.setText("");
        Emailtxt1.setText("");
        Telefonetxt1.setText("");
        Celulartxt1.setText("");
        Ceptxt1.setText("");
        Enderecotxt1.setText("");
        Numerotxt1.setText("");
        Complementotxt1.setText("");
       Bairrotxt1.setText("");
        Cidadetxt1.setText("");*/
       
       new Utilitarios().LimpaTela(PainelCadastroClientes);
       
    
    
    
    }
    
    
   public void listar(){
   
   ClientesDAO dao =  new ClientesDAO();
   List<Funcionarios> lista = dao.listarClientes();
   DefaultTableModel dados = (DefaultTableModel) TabelaClientes.getModel();
   dados.setNumRows(0);
   for(Funcionarios c : lista){
   
   dados.addRow(new Object[]{
   c.getId(),
   c.getNome(),
   c.getRg(),
   c.getCpf(),
   c.getEmail(),
   c.getTelefone(),
   c.getCelular(),
   c.getCep(),
   c.getEndereco(),
   c.getNumero(),
   c.getComplemento(),
   c.getBairro(),
   c.getCidade(),
   c.getEstado()
   
           
   
   });
   }
   
   
   }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        JTabbedPane = new javax.swing.JTabbedPane();
        PainelCadastroClientes = new javax.swing.JPanel();
        Codigotxt1 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        Nometxt1 = new javax.swing.JTextField();
        Btnpesquisar1 = new javax.swing.JButton();
        Emailtxt1 = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        Celulartxt1 = new javax.swing.JFormattedTextField();
        jLabel34 = new javax.swing.JLabel();
        Ceptxt1 = new javax.swing.JFormattedTextField();
        jLabel35 = new javax.swing.JLabel();
        Cpftxt1 = new javax.swing.JFormattedTextField();
        jLabel36 = new javax.swing.JLabel();
        Rgtxt1 = new javax.swing.JFormattedTextField();
        Complementotxt1 = new javax.swing.JTextField();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        Bairrotxt1 = new javax.swing.JTextField();
        jLabel39 = new javax.swing.JLabel();
        Enderecotxt1 = new javax.swing.JTextField();
        jLabel40 = new javax.swing.JLabel();
        Cidadetxt1 = new javax.swing.JTextField();
        Estadotxt1 = new javax.swing.JComboBox<>();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        Telefonetxt1 = new javax.swing.JFormattedTextField();
        BtnNovo = new javax.swing.JButton();
        BtnSalvar = new javax.swing.JButton();
        BtnEditar = new javax.swing.JButton();
        BtnExcluir = new javax.swing.JButton();
        Numerotxt1 = new javax.swing.JFormattedTextField();
        PainelConsultaClientes = new javax.swing.JPanel();
        PainelPesquisaClientes = new javax.swing.JLabel();
        txtpesquisar = new javax.swing.JTextField();
        btnPesquisar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TabelaClientes = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Cadastro de Clientes");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 468, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        JTabbedPane.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                JTabbedPaneStateChanged(evt);
            }
        });

        Codigotxt1.setEditable(false);

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel15.setText("Código:");

        jLabel31.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel31.setText("Nome:");

        Btnpesquisar1.setText("Pesquisar");
        Btnpesquisar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btnpesquisar1ActionPerformed(evt);
            }
        });

        jLabel32.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel32.setText("E-mail:");

        jLabel33.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel33.setText("Celular:");

        try {
            Celulartxt1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)#####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel34.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel34.setText("Cep:");

        try {
            Ceptxt1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        Ceptxt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Ceptxt1ActionPerformed(evt);
            }
        });
        Ceptxt1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                Ceptxt1KeyPressed(evt);
            }
        });

        jLabel35.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel35.setText("CPF:");

        try {
            Cpftxt1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        Cpftxt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cpftxt1ActionPerformed(evt);
            }
        });

        jLabel36.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel36.setText("RG:");

        try {
            Rgtxt1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-#")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel37.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel37.setText("Complemento:");

        jLabel38.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel38.setText("Bairro:");

        jLabel39.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel39.setText("Endereço:");

        Enderecotxt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Enderecotxt1ActionPerformed(evt);
            }
        });

        jLabel40.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel40.setText("Cidade:");

        Estadotxt1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "AC", "AL", "AP", "AM", "BA", "CE", "DF", "ES", "GO", "MA", "MT", "MS", "MG", "PA", "PB", "PR", "PE", "PI", "RJ", "RN", "RS", "RO", "RR", "SC", "SP", "SE", "TO" }));
        Estadotxt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Estadotxt1ActionPerformed(evt);
            }
        });

        jLabel41.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel41.setText("UF:");

        jLabel42.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel42.setText("Número:");

        jLabel43.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel43.setText("Telefone fixo:");

        try {
            Telefonetxt1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) ####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        BtnNovo.setText("NOVO");
        BtnNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnNovoActionPerformed(evt);
            }
        });

        BtnSalvar.setText("SALVAR");
        BtnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSalvarActionPerformed(evt);
            }
        });

        BtnEditar.setText("EDITAR");
        BtnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnEditarActionPerformed(evt);
            }
        });

        BtnExcluir.setText("EXCLUIR");
        BtnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnExcluirActionPerformed(evt);
            }
        });

        try {
            Numerotxt1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        javax.swing.GroupLayout PainelCadastroClientesLayout = new javax.swing.GroupLayout(PainelCadastroClientes);
        PainelCadastroClientes.setLayout(PainelCadastroClientesLayout);
        PainelCadastroClientesLayout.setHorizontalGroup(
            PainelCadastroClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelCadastroClientesLayout.createSequentialGroup()
                .addGroup(PainelCadastroClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PainelCadastroClientesLayout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addGroup(PainelCadastroClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PainelCadastroClientesLayout.createSequentialGroup()
                                .addGroup(PainelCadastroClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel31)
                                    .addComponent(jLabel15))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(PainelCadastroClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Codigotxt1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(PainelCadastroClientesLayout.createSequentialGroup()
                                        .addComponent(Nometxt1, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(Btnpesquisar1))))
                            .addGroup(PainelCadastroClientesLayout.createSequentialGroup()
                                .addComponent(jLabel32)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Emailtxt1, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(PainelCadastroClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, PainelCadastroClientesLayout.createSequentialGroup()
                                    .addGap(14, 14, 14)
                                    .addGroup(PainelCadastroClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel38)
                                        .addGroup(PainelCadastroClientesLayout.createSequentialGroup()
                                            .addComponent(jLabel35)
                                            .addGap(246, 246, 246)
                                            .addComponent(jLabel36)))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(PainelCadastroClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(PainelCadastroClientesLayout.createSequentialGroup()
                                            .addComponent(Bairrotxt1, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(jLabel42)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(Numerotxt1, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jLabel41)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(Estadotxt1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(0, 0, Short.MAX_VALUE))
                                        .addGroup(PainelCadastroClientesLayout.createSequentialGroup()
                                            .addComponent(Rgtxt1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel37)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(Complementotxt1, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jLabel43)
                                    .addGap(18, 18, 18)
                                    .addComponent(Telefonetxt1, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, PainelCadastroClientesLayout.createSequentialGroup()
                                    .addGroup(PainelCadastroClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(PainelCadastroClientesLayout.createSequentialGroup()
                                            .addComponent(jLabel33)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(Celulartxt1, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PainelCadastroClientesLayout.createSequentialGroup()
                                            .addGap(14, 14, 14)
                                            .addGroup(PainelCadastroClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PainelCadastroClientesLayout.createSequentialGroup()
                                                    .addComponent(jLabel34)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(Ceptxt1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addComponent(Cpftxt1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGap(74, 74, 74)
                                    .addComponent(jLabel39)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(Enderecotxt1, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jLabel40)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(Cidadetxt1, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(PainelCadastroClientesLayout.createSequentialGroup()
                        .addGap(354, 354, 354)
                        .addComponent(BtnNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(BtnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(BtnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(BtnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(91, Short.MAX_VALUE))
        );

        PainelCadastroClientesLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {BtnEditar, BtnExcluir, BtnNovo, BtnSalvar});

        PainelCadastroClientesLayout.setVerticalGroup(
            PainelCadastroClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelCadastroClientesLayout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addGroup(PainelCadastroClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(Codigotxt1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PainelCadastroClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel31)
                    .addComponent(Nometxt1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Btnpesquisar1))
                .addGap(13, 13, 13)
                .addGroup(PainelCadastroClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel32)
                    .addComponent(Emailtxt1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PainelCadastroClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel33)
                    .addComponent(Celulartxt1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel39)
                    .addComponent(Enderecotxt1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel40)
                    .addComponent(Cidadetxt1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PainelCadastroClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel42, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(PainelCadastroClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel34)
                        .addComponent(Ceptxt1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel38)
                        .addComponent(Bairrotxt1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel41)
                        .addComponent(Estadotxt1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Numerotxt1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PainelCadastroClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PainelCadastroClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel43)
                        .addComponent(Telefonetxt1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Complementotxt1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel37)
                        .addComponent(Rgtxt1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel36))
                    .addGroup(PainelCadastroClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Cpftxt1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel35)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 147, Short.MAX_VALUE)
                .addGroup(PainelCadastroClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnSalvar)
                    .addComponent(BtnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        PainelCadastroClientesLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {BtnEditar, BtnExcluir, BtnNovo, BtnSalvar});

        JTabbedPane.addTab("Dados Pessoais", PainelCadastroClientes);

        PainelConsultaClientes.setBackground(new java.awt.Color(255, 255, 255));
        PainelConsultaClientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PainelConsultaClientesMouseClicked(evt);
            }
        });

        PainelPesquisaClientes.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        PainelPesquisaClientes.setText("Nome:");

        txtpesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpesquisarActionPerformed(evt);
            }
        });
        txtpesquisar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtpesquisarKeyPressed(evt);
            }
        });

        btnPesquisar.setText("Pesquisar");
        btnPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarActionPerformed(evt);
            }
        });

        TabelaClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Nome", "RG", "CPF", "E-mail", "Telefone", "Celular", "Cep", "Endereço", "Número", "Complemento", "Bairro", "Cidade", "Estado"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TabelaClientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TabelaClientesMouseClicked(evt);
            }
        });
        TabelaClientes.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                TabelaClientesPropertyChange(evt);
            }
        });
        jScrollPane1.setViewportView(TabelaClientes);

        javax.swing.GroupLayout PainelConsultaClientesLayout = new javax.swing.GroupLayout(PainelConsultaClientes);
        PainelConsultaClientes.setLayout(PainelConsultaClientesLayout);
        PainelConsultaClientesLayout.setHorizontalGroup(
            PainelConsultaClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelConsultaClientesLayout.createSequentialGroup()
                .addGroup(PainelConsultaClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PainelConsultaClientesLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1227, Short.MAX_VALUE))
                    .addGroup(PainelConsultaClientesLayout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(PainelPesquisaClientes)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtpesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnPesquisar)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        PainelConsultaClientesLayout.setVerticalGroup(
            PainelConsultaClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelConsultaClientesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PainelConsultaClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PainelPesquisaClientes)
                    .addComponent(txtpesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPesquisar))
                .addGap(49, 49, 49)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(200, Short.MAX_VALUE))
        );

        JTabbedPane.addTab("Consulta Cliente", PainelConsultaClientes);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(JTabbedPane, javax.swing.GroupLayout.PREFERRED_SIZE, 1252, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(JTabbedPane, javax.swing.GroupLayout.PREFERRED_SIZE, 487, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Enderecotxt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Enderecotxt1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Enderecotxt1ActionPerformed

    private void Cpftxt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cpftxt1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Cpftxt1ActionPerformed

    private void Ceptxt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Ceptxt1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Ceptxt1ActionPerformed

    private void Estadotxt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Estadotxt1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Estadotxt1ActionPerformed

    private void BtnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSalvarActionPerformed
        // TODO add your handling code here:
        
        Funcionarios obj = new Funcionarios();
        obj.setNome(Nometxt1.getText());
        obj.setRg(Rgtxt1.getText());
        obj.setCpf(Cpftxt1.getText());
        obj.setEmail(Emailtxt1.getText());
        obj.setTelefone(Telefonetxt1.getText());
        obj.setCelular(Celulartxt1.getText());
        obj.setCep(Ceptxt1.getText());
        obj.setEndereco(Enderecotxt1.getText());
        obj.setNumero(Integer.parseInt(Numerotxt1.getText()));
        obj.setComplemento(Complementotxt1.getText());
        obj.setBairro(Bairrotxt1.getText());
        obj.setCidade(Cidadetxt1.getText());
        obj.setEstado(Estadotxt1.getSelectedItem().toString());
       
        ClientesDAO dao = new ClientesDAO();
        
        dao.cadastrarCliente(obj);
        
        
        limparCampos();
       
      
        
        
    }//GEN-LAST:event_BtnSalvarActionPerformed

    private void JTabbedPaneStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_JTabbedPaneStateChanged
        // TODO add your handling code here:
        
      
        
    }//GEN-LAST:event_JTabbedPaneStateChanged

    private void TabelaClientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TabelaClientesMouseClicked
        // TODO add your handling code here:
        
       JTabbedPane.setSelectedComponent(this.PainelCadastroClientes);
       Codigotxt1.setText(TabelaClientes.getValueAt(TabelaClientes.getSelectedRow(),0).toString());
       Nometxt1.setText(TabelaClientes.getValueAt(TabelaClientes.getSelectedRow(),1).toString());
       Rgtxt1.setText(TabelaClientes.getValueAt(TabelaClientes.getSelectedRow(),2).toString());
       Cpftxt1.setText(TabelaClientes.getValueAt(TabelaClientes.getSelectedRow(),3).toString());
       Emailtxt1.setText(TabelaClientes.getValueAt(TabelaClientes.getSelectedRow(),4).toString());
       Telefonetxt1.setText(TabelaClientes.getValueAt(TabelaClientes.getSelectedRow(),5).toString());
       Celulartxt1.setText(TabelaClientes.getValueAt(TabelaClientes.getSelectedRow(),6).toString());
       Ceptxt1.setText(TabelaClientes.getValueAt(TabelaClientes.getSelectedRow(),7).toString());
       Enderecotxt1.setText(TabelaClientes.getValueAt(TabelaClientes.getSelectedRow(),8).toString());
       Numerotxt1.setText(TabelaClientes.getValueAt(TabelaClientes.getSelectedRow(),9).toString());
       Complementotxt1.setText(TabelaClientes.getValueAt(TabelaClientes.getSelectedRow(),10).toString());
       Bairrotxt1.setText(TabelaClientes.getValueAt(TabelaClientes.getSelectedRow(),11).toString());
       Cidadetxt1.setText(TabelaClientes.getValueAt(TabelaClientes.getSelectedRow(),12).toString());
       Estadotxt1.setSelectedItem(TabelaClientes.getValueAt(TabelaClientes.getSelectedRow(),13).toString());
       
    }//GEN-LAST:event_TabelaClientesMouseClicked

    private void BtnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnEditarActionPerformed
        // TODO add your handling code here:
         Funcionarios obj = new Funcionarios();
        obj.setNome(Nometxt1.getText());
        obj.setRg(Rgtxt1.getText());
        obj.setCpf(Cpftxt1.getText());
        obj.setEmail(Emailtxt1.getText());
        obj.setTelefone(Telefonetxt1.getText());
        obj.setCelular(Celulartxt1.getText());
        obj.setCep(Ceptxt1.getText());
        obj.setEndereco(Enderecotxt1.getText());
        obj.setNumero(Integer.parseInt(Numerotxt1.getText()));
        obj.setComplemento(Complementotxt1.getText());
        obj.setBairro(Bairrotxt1.getText());
        obj.setCidade(Cidadetxt1.getText());
        obj.setEstado(Estadotxt1.getSelectedItem().toString());
        obj.setId(Integer.parseInt(Codigotxt1.getText()));
       
        ClientesDAO dao = new ClientesDAO();
        
        dao.alterarCliente(obj);
        
        limparCampos();
        
    }//GEN-LAST:event_BtnEditarActionPerformed

    private void BtnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnExcluirActionPerformed
        // TODO add your handling code here:
        
            Funcionarios obj = new Funcionarios();
     
        obj.setId(Integer.parseInt(Codigotxt1.getText()));
       
        ClientesDAO dao = new ClientesDAO();
        
        dao.excluirCliente(obj);
        
        
        limparCampos();
    }//GEN-LAST:event_BtnExcluirActionPerformed

    private void PainelConsultaClientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PainelConsultaClientesMouseClicked
        // TODO add your handling code here:
      
    }//GEN-LAST:event_PainelConsultaClientesMouseClicked

    private void TabelaClientesPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_TabelaClientesPropertyChange
        // TODO add your handling code here:
        
       
    }//GEN-LAST:event_TabelaClientesPropertyChange

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
        listar();
    }//GEN-LAST:event_formWindowActivated

    private void txtpesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpesquisarActionPerformed
        // TODO add your handling code here:

   
        
        
    }//GEN-LAST:event_txtpesquisarActionPerformed

    private void btnPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarActionPerformed
        // TODO add your handling code here:
        
   ClientesDAO dao =  new ClientesDAO();
   List<Funcionarios> lista = dao.listarClientesPorNome("%" + txtpesquisar.getText() + "%");
   DefaultTableModel dados = (DefaultTableModel) TabelaClientes.getModel();
   dados.setNumRows(0);
   for(Funcionarios c : lista){
   
   dados.addRow(new Object[]{
   c.getId(),
   c.getNome(),
   c.getRg(),
   c.getCpf(),
   c.getEmail(),
   c.getTelefone(),
   c.getCelular(),
   c.getCep(),
   c.getEndereco(),
   c.getNumero(),
   c.getComplemento(),
   c.getBairro(),
   c.getCidade(),
   c.getEstado()
   
           
   
   });
   }
        
        
    }//GEN-LAST:event_btnPesquisarActionPerformed

    private void txtpesquisarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtpesquisarKeyPressed
        // TODO add your handling code here:
        
   ClientesDAO dao =  new ClientesDAO();
   List<Funcionarios> lista = dao.listarClientesPorNome("%" + txtpesquisar.getText() + "%");
   DefaultTableModel dados = (DefaultTableModel) TabelaClientes.getModel();
   dados.setNumRows(0);
   for(Funcionarios c : lista){
   
   dados.addRow(new Object[]{
   c.getId(),
   c.getNome(),
   c.getRg(),
   c.getCpf(),
   c.getEmail(),
   c.getTelefone(),
   c.getCelular(),
   c.getCep(),
   c.getEndereco(),
   c.getNumero(),
   c.getComplemento(),
   c.getBairro(),
   c.getCidade(),
   c.getEstado()
   
           
   
   });
   }
        
        
    }//GEN-LAST:event_txtpesquisarKeyPressed

    private void BtnNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnNovoActionPerformed
        // TODO add your handling code here:
        
        limparCampos();
    }//GEN-LAST:event_BtnNovoActionPerformed

    private void Btnpesquisar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btnpesquisar1ActionPerformed
        // TODO add your handling code here:
        ClientesDAO dao = new ClientesDAO();
        Funcionarios obj = dao.consultarClientesPorNome(Nometxt1.getText());
        
        if(obj.getNome() != null){
        
        Codigotxt1.setText(String.valueOf(obj.getId()));
        Nometxt1.setText(obj.getNome());
        Rgtxt1.setText(obj.getRg());
       Cpftxt1.setText(obj.getCpf());
       Emailtxt1.setText(obj.getEmail());
       Telefonetxt1.setText(obj.getTelefone());
       Celulartxt1.setText(obj.getCelular());
       Ceptxt1.setText(obj.getCep());
       Enderecotxt1.setText(obj.getEndereco());
       Numerotxt1.setText(String.valueOf(obj.getNumero()));
       Complementotxt1.setText(obj.getComplemento());
       Bairrotxt1.setText(obj.getBairro());
       Cidadetxt1.setText(obj.getBairro());
       Estadotxt1.setSelectedItem(obj.getEstado());
        
        }else{
        JOptionPane.showMessageDialog(null, "Usuário não encontrado");
        
        }
        
        
    }//GEN-LAST:event_Btnpesquisar1ActionPerformed

    private void Ceptxt1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Ceptxt1KeyPressed
        // TODO add your handling code here:
        
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) { 
     Funcionarios obj = new ClientesDAO().buscaCep(Ceptxt1.getText());
      Enderecotxt1.setText(obj.getEndereco());
      Cidadetxt1.setText(obj.getCidade());
      Bairrotxt1.setText(obj.getBairro());
      Estadotxt1.setSelectedItem(obj.getEstado()); 
     }
        
     
        
    }//GEN-LAST:event_Ceptxt1KeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frmcliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frmcliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frmcliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frmcliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frmcliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Bairrotxt1;
    private javax.swing.JButton BtnEditar;
    private javax.swing.JButton BtnExcluir;
    private javax.swing.JButton BtnNovo;
    private javax.swing.JButton BtnSalvar;
    private javax.swing.JButton Btnpesquisar1;
    private javax.swing.JFormattedTextField Celulartxt1;
    private javax.swing.JFormattedTextField Ceptxt1;
    private javax.swing.JTextField Cidadetxt1;
    private javax.swing.JTextField Codigotxt1;
    private javax.swing.JTextField Complementotxt1;
    private javax.swing.JFormattedTextField Cpftxt1;
    private javax.swing.JTextField Emailtxt1;
    private javax.swing.JTextField Enderecotxt1;
    private javax.swing.JComboBox<String> Estadotxt1;
    private javax.swing.JTabbedPane JTabbedPane;
    private javax.swing.JTextField Nometxt1;
    private javax.swing.JFormattedTextField Numerotxt1;
    private javax.swing.JPanel PainelCadastroClientes;
    private javax.swing.JPanel PainelConsultaClientes;
    private javax.swing.JLabel PainelPesquisaClientes;
    private javax.swing.JFormattedTextField Rgtxt1;
    private javax.swing.JTable TabelaClientes;
    private javax.swing.JFormattedTextField Telefonetxt1;
    private javax.swing.JButton btnPesquisar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtpesquisar;
    // End of variables declaration//GEN-END:variables
}
